GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test1",
    "password": "test1",
    "gender": 1,
    "dateOfBirth": "2014-01-01T23:28:56.782Z",
    "email": "test1@email.com"
}

###


POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test2",
    "password": "test2",
    "gender": 1,
    "dateOfBirth": "2014-01-01T23:28:56.782Z",
    "email": "test2@email.com"
}

###

# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}

###
@authToken = {{login.response}}

# @name createComment
POST http://localhost:3000/friends 
Authorization: {{authToken.accessToken}}
Content-Type: application/json

{
    "friendUsername": "test2"
}
